// Generated by CoffeeScript 1.7.1
"use strict"
module.exports = angular.module("login", []).config([
  "$stateProvider", "$urlRouterProvider", ($stateProvider, $urlRouterProvider) => {
    $stateProvider.state("login", {
      url: "/login",
      controller:'loginCtrl',
      templateUrl: "modules/login/views/login.html",
      params: {
      	animateId:'body'
      }
    })
  }
])
.controller('loginCtrl', require('./controllers/login'))    
.controller('signOutCtrl', require('./controllers/sign.out')) 
.factory('loginService',require('./services/login'))
.directive('login',require('./directives/login'))
.directive('bgChanger',require('./directives/bg.changer'))

