// Generated by CoffeeScript 1.7.1
"use strict"
module.exports = angular.module("app", []).config([
  "$stateProvider", "$urlRouterProvider", ($stateProvider, $urlRouterProvider) => {
     $stateProvider.state("dashboard.app", {
      url: "/app",
      views:{
        'func':{
           controller:'AppCtrl',
           templateUrl: "modules/app/views/app.html",
        }
      }
    })
    .state("dashboard.app.list",{
      url:"/list",
      views:{
        'app':{
          controller:'AppManageCtrl',
          templateUrl: "modules/app/views/app.manage.html"
        }
      },
      params:{
        param:null   
      }
    })
  }
]) 

.controller('AppManageCtrl', require('./controllers/app.manage'))
.controller('AppCtrl', require('./controllers/app')) 
.controller('addAppCtrl', require('./controllers/app.add')) 
.controller('editAppCtrl', require('./controllers/app.edit')) 
.controller('appUsersCtrl', require('./controllers/app.users')) 
.directive('appAside', require('./directives/app.aside'))
.directive('appManage', require('./directives/app.manage'))
.factory('appManageService',require('./services/app.manage'))
.factory('appResourceService',require('./services/app.resource'))


