// Generated by CoffeeScript 1.7.1
"use strict"
module.exports = angular.module("content", []).config([
  "$stateProvider", "$urlRouterProvider", ($stateProvider, $urlRouterProvider) => {

    // $stateProvider.state("dashboard", {
    //   url: "/dashboard",
    //   templateUrl: "modules/dashboard/views/dashboard.html",
    //   params: {id: null}
    // })
    // .state("dashboard.general",{
    //   url:"/dashboard/general",
    //   templateUrl: "modules/content/views/general.html",
    //   params:{
    //   	param:null
    //   }
    // })
  }
])
/**
 * @ngdoc directive
 * @name content.directive:general
 * @restrict E
 * @description
 * 图表基本组件,整个应用最核心的组件
 *
 * @property {Array} tableTitles 表格的表头
 * @property {Object} generalData 从后台请求过来的数据
 * 
 * @requires content.service:reqDataService
 * 
 */
.directive('general', require('./directives/stand/general'))
/**
 * @ngdoc directive
 * @name content.directive:realtime
 * @restrict E
 * @description
 * 实时图表基本组件
 *
 * @property {Array} tableTitles 表格的表头
 * @property {Object} generalData 从后台请求过来的数据
 * 
 * @requires content.service:reqDataService
 * 
 */
.directive('realtime', require('./directives/stand/realtime'))
.directive('crashException', require('./directives/crash/crash.exception'))
.directive('crashTable', require('./directives/crash/crash.table'))
.factory('DataModel',require('./models/data.model'))   
/**
 * @ngdoc service
 * @name content.service:dataParserService
 * @requires content.service:dataOperationService
 * @description
 * 后台菜单JSON配置解析服务,根据配置信息生成echarts配置
 */
.factory('dataParserService',require('./services/data.parser'))  
/**
 * @ngdoc service
 * @name content.service:reqDataService
 * @requires common.service:MobileService
 * @requires common.service:Notification
 * @requires dashboard.service:dashboardService
 * @description
 * 图表数据请求服务，对MobileService进行了一次业务封装
 */
.factory('reqDataService',require('./services/req.data'))  
/**
 * @ngdoc service
 * @name content.service:dataOperationService
 * @description
 * 数据操作解析服务
 */
.factory('dataOperationService',require('./services/data.operation')) 
.factory('crashService',require('./services/crash.service')) 
.factory('crashResource',require('./services/crash.resource')) 
.controller('crashResolveCtrl', require('./controllers/crash.resolve.js'))
.controller('crashInfoCtrl', require('./controllers/crash.info.js'))
.controller('crashHistoryCtrl', require('./controllers/crash.history.js'))

// .constant('customerMock',require('./customer.mock'))
// .directive('faceLook', require('./directives/face.look')) 
// .directive('finishrender', require('./directives/finish.render'))
// .factory('ChatService', require('./services/chat.service'))
// .controller('recentChatListCtrl', require('./controllers/recentChat.list'))

