"use strict";

module.exports = [
  "$scope",'crashData','infoData','$uibModalInstance','Notification',
  ($scope,crashData,infoData,$uibModalInstance,Notification)=>{
    $scope.curIndex = 0
    $scope.tabs = [{
      text:'StackTrace详情'
    },{
      text:'异常明细列表'  
    }]
    $scope.htmllist = []
    let collapsed
    infoData.stack_trace.forEach((trace,ti)=>{
        $scope.htmllist.push({
            name:`第${ti+1}条stack_trace`,
            content:trace,
            collapsed : true
        })
    })

    // $scope.htmllist = [
    // {name:'第一条',content:'<div style="color:green;font-size:16px;">java.lang.OutOfMemoryError<br>  at android.graphics.Bitmap.nativeCreate(Native Method)<br>  at android.graphics.Bitmap.createBitmap(Bitmap.java:605)<br>  at android.graphics.Bitmap.createBitmap(Bitmap.java:551)<br>  at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:437)<br>  at android.graphics.BitmapFactory.finishDecode(BitmapFactory.java:524)<br>  at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:499)<br>  at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:351)<br>  at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:773)<br> at android.content.res.Resources.loadDrawable(Resources.java:1935)<br>  at android.content.res.Resources.getDrawable(Resources.java:664)<br>  at android.view.View.setBackgroundResource(View.java:11695)<br> at com.moretv.android.bk.a(Unknown Source)<br>  at com.moretv.baseView.cb.e(Unknown Source)<br> at com.moretv.baseView.cb.dispatchKeyEvent(Unknown Source)<br>  at com.moretv.android.SettingActivity.keyOk(Unknown Source)<br> at com.moretv.baseView.BaseActivity.normalKeyDownEvent(Unknown Source)<br>  at com.moretv.baseView.BaseActivity.dispatchKeyEvent(Unknown Source)<br>  at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:1898)<br> at android.view.ViewRootImpl.deliverKeyEventPostIme(ViewRootImpl.java:3327)<br> at android.view.ViewRootImpl.handleFinishedEvent(ViewRootImpl.java:3300)<br>  at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2460)<br>  at android.os.Handler.dispatchMessage(Handler.java:99)<br>  at android.os.Looper.loop(Looper.java:137)<br>  at android.app.ActivityThread.main(ActivityThread.java:4424)<br>  at java.lang.reflect.Method.invokeNative(Native Method)<br> at java.lang.reflect.Method.invoke(Method.java:511)<br> at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)<br>  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)<br> at dalvik.system.NativeStart.main(Native Method)<br><br></div>',collapsed:true},
    // {name:'第二条',content:'<div style="color:green;font-size:16px;">java.lang.OutOfMemoryError<br>  at android.graphics.Bitmap.nativeCreate(Native Method)<br>  at android.graphics.Bitmap.createBitmap(Bitmap.java:605)<br>  at android.graphics.Bitmap.createBitmap(Bitmap.java:551)<br>  at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:437)<br>  at android.graphics.BitmapFactory.finishDecode(BitmapFactory.java:524)<br>  at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:499)<br>  at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:351)<br>  at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:773)<br> at android.content.res.Resources.loadDrawable(Resources.java:1935)<br>  at android.content.res.Resources.getDrawable(Resources.java:664)<br>  at android.view.View.setBackgroundResource(View.java:11695)<br> at com.moretv.android.bk.a(Unknown Source)<br>  at com.moretv.baseView.cb.e(Unknown Source)<br> at com.moretv.baseView.cb.dispatchKeyEvent(Unknown Source)<br>  at com.moretv.android.SettingActivity.keyOk(Unknown Source)<br> at com.moretv.baseView.BaseActivity.normalKeyDownEvent(Unknown Source)<br>  at com.moretv.baseView.BaseActivity.dispatchKeyEvent(Unknown Source)<br>  at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:1898)<br> at android.view.ViewRootImpl.deliverKeyEventPostIme(ViewRootImpl.java:3327)<br> at android.view.ViewRootImpl.handleFinishedEvent(ViewRootImpl.java:3300)<br>  at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2460)<br>  at android.os.Handler.dispatchMessage(Handler.java:99)<br>  at android.os.Looper.loop(Looper.java:137)<br>  at android.app.ActivityThread.main(ActivityThread.java:4424)<br>  at java.lang.reflect.Method.invokeNative(Native Method)<br> at java.lang.reflect.Method.invoke(Method.java:511)<br> at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)<br>  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)<br> at dalvik.system.NativeStart.main(Native Method)<br><br></div>',collapsed:true},
    // {name:'第三条',content:'<div style="color:green;font-size:16px;">java.lang.OutOfMemoryError<br>  at android.graphics.Bitmap.nativeCreate(Native Method)<br>  at android.graphics.Bitmap.createBitmap(Bitmap.java:605)<br>  at android.graphics.Bitmap.createBitmap(Bitmap.java:551)<br>  at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:437)<br>  at android.graphics.BitmapFactory.finishDecode(BitmapFactory.java:524)<br>  at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:499)<br>  at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:351)<br>  at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:773)<br> at android.content.res.Resources.loadDrawable(Resources.java:1935)<br>  at android.content.res.Resources.getDrawable(Resources.java:664)<br>  at android.view.View.setBackgroundResource(View.java:11695)<br> at com.moretv.android.bk.a(Unknown Source)<br>  at com.moretv.baseView.cb.e(Unknown Source)<br> at com.moretv.baseView.cb.dispatchKeyEvent(Unknown Source)<br>  at com.moretv.android.SettingActivity.keyOk(Unknown Source)<br> at com.moretv.baseView.BaseActivity.normalKeyDownEvent(Unknown Source)<br>  at com.moretv.baseView.BaseActivity.dispatchKeyEvent(Unknown Source)<br>  at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:1898)<br> at android.view.ViewRootImpl.deliverKeyEventPostIme(ViewRootImpl.java:3327)<br> at android.view.ViewRootImpl.handleFinishedEvent(ViewRootImpl.java:3300)<br>  at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2460)<br>  at android.os.Handler.dispatchMessage(Handler.java:99)<br>  at android.os.Looper.loop(Looper.java:137)<br>  at android.app.ActivityThread.main(ActivityThread.java:4424)<br>  at java.lang.reflect.Method.invokeNative(Native Method)<br> at java.lang.reflect.Method.invoke(Method.java:511)<br> at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)<br>  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)<br> at dalvik.system.NativeStart.main(Native Method)<br><br></div>',collapsed:true},
    // {name:'第四条',content:'<div style="color:green;font-size:16px;">java.lang.OutOfMemoryError<br>  at android.graphics.Bitmap.nativeCreate(Native Method)<br>  at android.graphics.Bitmap.createBitmap(Bitmap.java:605)<br>  at android.graphics.Bitmap.createBitmap(Bitmap.java:551)<br>  at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:437)<br>  at android.graphics.BitmapFactory.finishDecode(BitmapFactory.java:524)<br>  at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:499)<br>  at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:351)<br>  at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:773)<br> at android.content.res.Resources.loadDrawable(Resources.java:1935)<br>  at android.content.res.Resources.getDrawable(Resources.java:664)<br>  at android.view.View.setBackgroundResource(View.java:11695)<br> at com.moretv.android.bk.a(Unknown Source)<br>  at com.moretv.baseView.cb.e(Unknown Source)<br> at com.moretv.baseView.cb.dispatchKeyEvent(Unknown Source)<br>  at com.moretv.android.SettingActivity.keyOk(Unknown Source)<br> at com.moretv.baseView.BaseActivity.normalKeyDownEvent(Unknown Source)<br>  at com.moretv.baseView.BaseActivity.dispatchKeyEvent(Unknown Source)<br>  at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:1898)<br> at android.view.ViewRootImpl.deliverKeyEventPostIme(ViewRootImpl.java:3327)<br> at android.view.ViewRootImpl.handleFinishedEvent(ViewRootImpl.java:3300)<br>  at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2460)<br>  at android.os.Handler.dispatchMessage(Handler.java:99)<br>  at android.os.Looper.loop(Looper.java:137)<br>  at android.app.ActivityThread.main(ActivityThread.java:4424)<br>  at java.lang.reflect.Method.invokeNative(Native Method)<br> at java.lang.reflect.Method.invoke(Method.java:511)<br> at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)<br>  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)<br> at dalvik.system.NativeStart.main(Native Method)<br><br></div>',collapsed:true}
    // ]
    $scope.tableData = infoData
    $scope.changeTab = (tab,index,tabs)=>{
      $scope.curIndex = index
    }
  	$scope.ok = () => {
      $uibModalInstance.close()
  	};

  	$scope.cancel =  () => {
  	  $uibModalInstance.dismiss('cancel')
  	};

  	$scope.$on('$destroy',()=>{
  		$uibModalInstance.dismiss('cancel')
  	})
  }
]