// Generated by CoffeeScript 1.7.1
"use strict";
module.exports = angular.module("config", [])
  /**
 * @ngdoc object
 * @name config.object:Env
 * @description
 * 当前应用的配置
 * @property {string} env 运行环境(development|production)
 */
  .constant('Env', require('./config/env.config'))
    /**
 * @ngdoc object
 * @name config.object:ServerList
 * @description
 * 远程服务URL列表
 * @property {Object} helios helios生产环境
 * @property {Object} production medusa生产环境
 * @property {Object} testHelios helios测试环境
 * @property {Object} testMedusa medusa测试环境
 * @property {Object} development 开发环境
 */
  .constant('ServerList', require('./config/server.config.list'))  
      /**
 * @ngdoc object
 * @name config.object:EchartTheme
 * @description
 * Echart默认配置
 */
  .constant('EchartTheme', require('./config/echart.theme'))  

  .constant('SelectList',require('./config/select.list'))
  .constant('Memorykey',require('./config/memory.key'))
        /**
 * @ngdoc object
 * @name config.object:AppMenu
 * @description
 * 应用管理菜单
 */
  .constant('AppMenu',require('./config/app.menu'))
   /**
 * @ngdoc object
 * @name config.object:MenuIcon
 * @description
 * 菜单图标
 * 
 */
  .constant('MenuIcon',require('./config/menu.icon'))
  /**
 * @ngdoc service
 * @name config.service:ServerCurrent
 * @description
 * 当前应用的配置
 */
  .factory('ServerCurrent', require('./config/server.config.current'))
